const router = require('express').Router();
const mongoose = require('mongoose');
const { Order, Product, Address } = require('../models');
const { auth, admin } = require('../middleware');
router.use(auth);
router.post('/', async (req, res, next) => { const session = await mongoose.startSession(); try { let created; await session.withTransaction(async () => { const input = req.body; const address = input.addressId ? await Address.findOne({ _id: input.addressId, user: req.user._id }).lean().session(session) : input.address; if (!address) { const e = new Error('A delivery address is required'); e.status = 400; throw e; } const ids = (input.items || []).map(i => i.productId); const products = await Product.find({ _id: { $in: ids }, isActive: true }).session(session); const byId = Object.fromEntries(products.map(p => [String(p._id), p])); const items = []; let subtotal = 0; for (const line of input.items || []) { const p = byId[line.productId]; const qty = Number(line.quantity); if (!p || !Number.isInteger(qty) || qty < 1) { const e = new Error('Invalid product or quantity'); e.status = 400; throw e; } if (p.stock < qty) { const e = new Error(`${p.name} has only ${p.stock} left in stock`); e.status = 409; throw e; } p.stock -= qty; await p.save({ session }); subtotal += p.price * qty; items.push({ product: p._id, name: p.name, image: p.images?.[0], quantity: qty, price: p.price, unit: p.unit }); } const discount = Number(input.discount || 0); const deliveryFee = Number(input.deliveryFee || 0); [created] = await Order.create([{ user: req.user._id, items, subtotal, discount, deliveryFee, total: subtotal - discount + deliveryFee, paymentMethod: 'COD', address: { fullName: address.fullName, mobile: address.mobile, line1: address.line1, line2: address.line2, city: address.city, state: address.state, pincode: address.pincode, label: address.label } }], { session }); }); const order = await Order.findById(created._id).lean(); res.status(201).json({ success: true, data: normalize(order) }); } catch (e) { next(e); } finally { await session.endSession(); } });
router.get('/', async (req, res, next) => { try { const rows = await Order.find({ user: req.user._id }).sort({ createdAt: -1 }).lean(); res.json({ success: true, data: rows.map(normalize) }); } catch (e) { next(e); } });
router.get('/admin/all', admin, async (req, res, next) => { try { const rows = await Order.find().populate('user', 'fullName email mobile').sort({ createdAt: -1 }).lean(); res.json({ success: true, data: rows.map(normalize) }); } catch (e) { next(e); } });
router.patch('/admin/:id/status', admin, async (req, res, next) => { try { const allowed = ['placed', 'confirmed', 'packed', 'shipped', 'delivered', 'cancelled']; if (!allowed.includes(req.body.status)) return res.status(400).json({ success: false, message: 'Invalid order status' }); const o = await Order.findByIdAndUpdate(req.params.id, { status: req.body.status }, { new: true }).lean(); res.json({ success: true, data: normalize(o) }); } catch (e) { next(e); } });
router.get('/:id', async (req, res, next) => { try { const o = await Order.findOne({ _id: req.params.id, user: req.user._id }).lean(); if (!o) return res.status(404).json({ success: false, message: 'Order not found' }); res.json({ success: true, data: normalize(o) }); } catch (e) { next(e); } });
function normalize(o) { return { ...o, id: o._id, placedAt: o.createdAt, address: o.address, items: o.items?.map(i => ({ ...i, productId: i.product })) }; }
module.exports = router;
