import React, { useCallback, useState } from "react";
import { View, Text, StyleSheet, FlatList, RefreshControl } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router, useFocusEffect } from "expo-router";
import { ArrowLeft, Package } from "lucide-react-native";
import { colors, spacing, typography, radius } from "@/theme";
import { orderService } from "@/services";
import { Order } from "@/types";
import { formatPrice } from "@/utils/format";

type StoredItem = { name?: string; quantity: number; price?: number; unit?: string };

export default function OrdersScreen() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { setRefreshing(true); try { setOrders(await orderService.getOrders()); } finally { setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  return <SafeAreaView style={styles.container} edges={["top"]}><View style={styles.header}><ArrowLeft size={21} color={colors.text.primary} onPress={() => router.back()} /><Text style={styles.title}>My Orders</Text><View style={{ width: 21 }} /></View><FlatList data={orders} keyExtractor={(order) => order.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={load} />} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Package size={40} color={colors.primary.organic} /><Text style={styles.emptyTitle}>No orders yet</Text><Text style={styles.emptyText}>Your completed purchases will appear here.</Text></View>} renderItem={({ item }) => { const storedItems = (item.items || []) as unknown as StoredItem[]; const itemTotal = storedItems.reduce((sum, line) => sum + (Number(line.price) || 0) * line.quantity, 0); const total = Number(item.total) || itemTotal; return <View style={styles.card}><View style={styles.row}><Text style={styles.orderId}>Order #{String(item.id).slice(-8).toUpperCase()}</Text><Text style={styles.status}>{item.status}</Text></View><Text style={styles.meta}>{storedItems.length} item{storedItems.length === 1 ? "" : "s"} · {new Date(item.placedAt).toLocaleDateString()}</Text>{storedItems.slice(0, 3).map((line, index) => <View key={`${item.id}-${index}`} style={styles.itemRow}><Text style={styles.itemName} numberOfLines={1}>{line.name || "Product"} × {line.quantity}</Text><Text style={styles.itemPrice}>{line.price != null ? formatPrice(line.price * line.quantity) : "—"}</Text></View>)}<View style={styles.totalRow}><Text style={styles.totalLabel}>Order total</Text><Text style={styles.total}>{formatPrice(total)}</Text></View></View>; }} /></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background.default }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.lg, paddingBottom: spacing.md }, title: { ...typography.h2, fontSize: 19, color: colors.text.primary }, list: { padding: spacing.lg, flexGrow: 1 }, card: { backgroundColor: colors.background.card, borderRadius: radius.lg, padding: spacing.lg, marginBottom: spacing.md }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, orderId: { ...typography.productTitle, color: colors.text.primary }, status: { ...typography.bodySmall, color: colors.primary.organic, textTransform: "capitalize" }, meta: { ...typography.bodySmall, color: colors.text.secondary, marginTop: spacing.xs }, itemRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: spacing.sm }, itemName: { ...typography.bodySmall, color: colors.text.primary, flex: 1, marginRight: spacing.sm }, itemPrice: { ...typography.bodySmall, color: colors.text.secondary }, totalRow: { borderTopWidth: 1, borderTopColor: colors.border.light, marginTop: spacing.md, paddingTop: spacing.sm, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, totalLabel: { ...typography.bodySmall, color: colors.text.secondary }, total: { ...typography.h2, fontSize: 18, color: colors.text.primary }, empty: { flex: 1, alignItems: "center", justifyContent: "center" }, emptyTitle: { ...typography.h2, color: colors.text.primary, marginTop: spacing.md }, emptyText: { ...typography.body, color: colors.text.secondary, marginTop: spacing.xs } });
